// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: character.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from character.proto</summary>
  public static partial class CharacterReflection {

    #region Descriptor
    /// <summary>File descriptor for character.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CharacterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9jaGFyYWN0ZXIucHJvdG8SCHByb3RvYnVmGgpoZXJvLnByb3RvGgppdGVt",
            "LnByb3RvInUKCWNoYXJhY3RlchIKCgJpZBgBIAEoCRIPCgd1c2VuYW1lGAIg",
            "ASgJEg0KBWxldmVsGAMgASgJEh0KBWhlcm9zGAQgAygLMg4ucHJvdG9idWYu",
            "aGVybxIdCgVpdGVtcxgFIAMoCzIOLnByb3RvYnVmLml0ZW1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protobuf.HeroReflection.Descriptor, global::Protobuf.ItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.character), global::Protobuf.character.Parser, new[]{ "Id", "Usename", "Level", "Heros", "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class character : pb::IMessage<character> {
    private static readonly pb::MessageParser<character> _parser = new pb::MessageParser<character>(() => new character());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<character> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.CharacterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public character() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public character(character other) : this() {
      id_ = other.id_;
      usename_ = other.usename_;
      level_ = other.level_;
      heros_ = other.heros_.Clone();
      items_ = other.items_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public character Clone() {
      return new character(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "usename" field.</summary>
    public const int UsenameFieldNumber = 2;
    private string usename_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Usename {
      get { return usename_; }
      set {
        usename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 3;
    private string level_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Level {
      get { return level_; }
      set {
        level_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "heros" field.</summary>
    public const int HerosFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Protobuf.hero> _repeated_heros_codec
        = pb::FieldCodec.ForMessage(34, global::Protobuf.hero.Parser);
    private readonly pbc::RepeatedField<global::Protobuf.hero> heros_ = new pbc::RepeatedField<global::Protobuf.hero>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Protobuf.hero> Heros {
      get { return heros_; }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Protobuf.item> _repeated_items_codec
        = pb::FieldCodec.ForMessage(42, global::Protobuf.item.Parser);
    private readonly pbc::RepeatedField<global::Protobuf.item> items_ = new pbc::RepeatedField<global::Protobuf.item>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Protobuf.item> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as character);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(character other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Usename != other.Usename) return false;
      if (Level != other.Level) return false;
      if(!heros_.Equals(other.heros_)) return false;
      if(!items_.Equals(other.items_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Usename.Length != 0) hash ^= Usename.GetHashCode();
      if (Level.Length != 0) hash ^= Level.GetHashCode();
      hash ^= heros_.GetHashCode();
      hash ^= items_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Usename.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Usename);
      }
      if (Level.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Level);
      }
      heros_.WriteTo(output, _repeated_heros_codec);
      items_.WriteTo(output, _repeated_items_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Usename.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Usename);
      }
      if (Level.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Level);
      }
      size += heros_.CalculateSize(_repeated_heros_codec);
      size += items_.CalculateSize(_repeated_items_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(character other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Usename.Length != 0) {
        Usename = other.Usename;
      }
      if (other.Level.Length != 0) {
        Level = other.Level;
      }
      heros_.Add(other.heros_);
      items_.Add(other.items_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Usename = input.ReadString();
            break;
          }
          case 26: {
            Level = input.ReadString();
            break;
          }
          case 34: {
            heros_.AddEntriesFrom(input, _repeated_heros_codec);
            break;
          }
          case 42: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
